-- Q1:
CREATE OR REPLACE PROCEDURE CHECK_SALARY(
    JOBID VARCHAR2,
    SAL NUMBER
) IS
    MAXSAL NUMBER;
    MINSAL NUMBER;
BEGIN
    SELECT
        MIN_SALARY,
        MAX_SALARY INTO MINSAL,
        MAXSAL
    FROM
        JOBS
    WHERE
        JOB_ID = JOBID;
    IF(SAL NOT IN (MAXSAL, MINSAL)) THEN
        RAISE_APPLICATION_ERROR(-20202, 'Employee salary not in the accepted range for the job');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER CHECK_SALARY_TRIG BEFORE
    INSERT OR UPDATE OF SALARY OR UPDATE OF JOB_ID ON EMPLOYEES FOR EACH ROW
BEGIN
    CHECK_SALARY (:NEW.JOB_ID, :NEW.SALARY);
END;
/

-- Q3:
CREATE OR REPLACE TRIGGER CHECK_SALARY_TRIG BEFORE
    INSERT OR UPDATE OF SALARY OR UPDATE OF JOB_ID ON EMPLOYEES FOR EACH ROW
BEGIN
    CHECK_SALARY (:NEW.JOB_ID, :NEW.SALARY);
END;
/

-- Q4 (Section Task):
CREATE OR REPLACE TRIGGER DELETE_EMP_TRG BEFORE
    DELETE ON EMPLOYEES
BEGIN
    IF NOT (TO_CHAR(SYSDATE(), 'DY') IN ('SAT', 'SUN')
    OR TO_CHAR(SYSDATE(), 'HH24:MI') NOT BETWEEN '08:00'
    AND '18:00') THEN
        RAISE_APPLICATION_ERROR(-20500, 'You may delete from EMPLOYEES table only during business hours.');
    END IF;
END;
/